import { Bike, Car, Plane, Ship, Siren, Truck } from "lucide-react";

import type { CatalogConfig } from "./catalog-types";

export const transportConfig: CatalogConfig = {
  domain: "transport",
  basePath: "/dashboard/transport",
  metaTitle: "Транспорт — каталог транспортных средств",
  metaDescription:
    "Каталог транспорта проекта: легковые, мотоциклы, грузовой, воздушный, водный и служебный транспорт.",
  title: "Транспорт",
  subtitle: "Каталог транспортных средств: находите, группируйте и отслеживайте модели.",
  addLabel: "Добавить транспорт",
  addDialogTitle: "Добавить транспорт",
  addDialogDescription: "Новая модель появится в каталоге. Данные сохраняются в этом браузере.",
  namePlaceholder: "Например, Седан «Бриз»",
  defaultOwner: "Гражданские",
  entryAddedMessage: "Транспорт добавлен",
  newCategoryLabel: "Новая категория",
  searchPlaceholder: "Поиск по транспорту и категориям...",
  categoriesTitle: "Категории",
  categoriesEmptyTitle: "Категорий пока нет",
  categoriesEmptyDescription: "Создайте категорию, чтобы упорядочить транспорт.",
  allTitle: "Весь транспорт",
  viewLabel: "Вид каталога",
  kindFilterLabel: "Тип транспорта",
  ownerColumn: "Доступ",
  sharedLabel: "В продаже",
  entryForms: ["модель", "модели", "моделей"],
  categoryForms: ["категория", "категории", "категорий"],
  kinds: [
    { value: "car", label: "Легковой", icon: Car },
    { value: "moto", label: "Мотоцикл", icon: Bike },
    { value: "truck", label: "Грузовой", icon: Truck },
    { value: "air", label: "Воздушный", icon: Plane },
    { value: "water", label: "Водный", icon: Ship },
    { value: "special", label: "Служебный", icon: Siren },
  ],
  detailSections: [
    {
      id: "specs",
      title: "Характеристики",
      fields: [
        { key: "maxSpeed", label: "Максимальная скорость", type: "number", unit: "км/ч", placeholder: "300" },
        { key: "maxSpeedFt", label: "Максимальная скорость (FT)", type: "number", unit: "км/ч", placeholder: "335" },
        { key: "transferable", label: "Возможность передачи", type: "boolean" },
        { key: "trunk", label: "Вместимость багажника", type: "number", unit: "кг", placeholder: "70" },
        {
          key: "fuel",
          label: "Тип топлива",
          type: "select",
          options: ["Бензин", "Дизель", "Электричество", "Premium"],
        },
        { key: "driftChip", label: "Дрифт-чип", type: "boolean" },
        { key: "nitro", label: "Нитро", type: "boolean" },
        { key: "uniqueId", label: "Уникальный ID", type: "text", placeholder: "boattail" },
      ],
    },
    {
      id: "about",
      title: "Описание и получение",
      fields: [
        { key: "description", label: "Описание", type: "textarea", placeholder: "Кратко о транспорте" },
        { key: "source", label: "Источник получения", type: "text", placeholder: "Автосалон" },
      ],
    },
    {
      id: "upgrades",
      title: "Улучшения транспорта",
      totalLabel: "Стоимость улучшений",
      fields: [
        { key: "upgEngine", label: "Двигатель", type: "money", unit: "$" },
        { key: "upgGearbox", label: "Коробка", type: "money", unit: "$" },
        { key: "upgTurbo", label: "Турбо", type: "money", unit: "$" },
        { key: "upgBrakes", label: "Тормоза", type: "money", unit: "$" },
        { key: "upgSuspension", label: "Подвеска", type: "money", unit: "$" },
      ],
    },
  ],
  categories: [
    { id: "cars", name: "Легковые", count: 24, priceFrom: "от $8 500", updatedAt: "12 мин назад" },
    { id: "moto", name: "Мотоциклы", count: 14, priceFrom: "от $3 200", updatedAt: "Вчера" },
    { id: "trucks", name: "Грузовой транспорт", count: 9, priceFrom: "от $31 000", updatedAt: "26 сентября" },
    { id: "air", name: "Авиация", count: 7, priceFrom: "от $480 000", updatedAt: "24 сентября" },
    { id: "water", name: "Водный транспорт", count: 11, priceFrom: "от $12 000", updatedAt: "22 сентября" },
    { id: "special", name: "Служебный транспорт", count: 18, priceFrom: "—", updatedAt: "19 сентября" },
  ],
  entries: [
    {
      id: "boattail",
      name: "Merlin Boat Tayl",
      kind: "car",
      price: "—",
      owner: "Подписка",
      ownerInitials: "ПД",
      modifiedAt: "Только что",
      shared: false,
      starred: true,
      isNew: true,
      details: {
        maxSpeed: "300",
        maxSpeedFt: "335",
        transferable: "no",
        trunk: "70",
        fuel: "Premium",
        driftChip: "no",
        nitro: "yes",
        uniqueId: "boattail",
        description: "Транспорт за 660 дней активной подписки",
        source: "Majestic Премиум",
        upgEngine: "369600",
        upgGearbox: "118800",
        upgTurbo: "101200",
        upgBrakes: "59400",
        upgSuspension: "15000",
      },
    },
    {
      id: "sedan-briz",
      name: "Седан «Бриз»",
      kind: "car",
      price: "$14 500",
      owner: "Гражданские",
      ownerInitials: "ГР",
      modifiedAt: "5 минут назад",
      shared: true,
      starred: true,
      details: {
        maxSpeed: "185",
        maxSpeedFt: "205",
        transferable: "yes",
        trunk: "60",
        fuel: "Бензин",
        driftChip: "no",
        nitro: "no",
        uniqueId: "sedan-briz",
        description: "Надёжный городской седан для повседневных поездок.",
        source: "Автосалон",
        upgEngine: "45000",
        upgGearbox: "18000",
        upgTurbo: "30000",
        upgBrakes: "12000",
        upgSuspension: "6000",
      },
    },
    {
      id: "suv-bars",
      name: "Внедорожник «Барс»",
      kind: "car",
      price: "$38 000",
      owner: "Гражданские",
      ownerInitials: "ГР",
      modifiedAt: "2 часа назад",
      shared: true,
      starred: false,
    },
    {
      id: "sport-molniya",
      name: "Спорткар «Молния»",
      kind: "car",
      price: "$120 000",
      owner: "Гражданские",
      ownerInitials: "ГР",
      modifiedAt: "Вчера",
      shared: true,
      starred: true,
      details: {
        maxSpeed: "290",
        maxSpeedFt: "320",
        transferable: "yes",
        trunk: "25",
        fuel: "Premium",
        driftChip: "yes",
        nitro: "yes",
        uniqueId: "sport-molniya",
        description: "Спорткар с агрессивной подвеской и максимальным набором улучшений.",
        source: "Премиум-салон",
        upgEngine: "320000",
        upgGearbox: "110000",
        upgTurbo: "95000",
        upgBrakes: "52000",
        upgSuspension: "14000",
      },
    },
    {
      id: "moto-gepard",
      name: "Мотоцикл «Гепард»",
      kind: "moto",
      price: "$22 000",
      owner: "Гражданские",
      ownerInitials: "ГР",
      modifiedAt: "27 сентября 2026",
      shared: true,
      starred: false,
    },
    {
      id: "enduro-taiga",
      name: "Эндуро «Тайга»",
      kind: "moto",
      price: "$9 800",
      owner: "Гражданские",
      ownerInitials: "ГР",
      modifiedAt: "26 сентября 2026",
      shared: true,
      starred: false,
    },
    {
      id: "van-gruz-7",
      name: "Фургон «Груз-7»",
      kind: "truck",
      price: "$46 000",
      owner: "Грузоперевозки",
      ownerInitials: "ГП",
      modifiedAt: "25 сентября 2026",
      shared: true,
      starred: false,
    },
    {
      id: "tractor-titan",
      name: "Тягач «Титан»",
      kind: "truck",
      price: "$95 000",
      owner: "Грузоперевозки",
      ownerInitials: "ГП",
      modifiedAt: "24 сентября 2026",
      shared: false,
      starred: true,
    },
    {
      id: "heli-strizh",
      name: "Вертолёт «Стриж»",
      kind: "air",
      price: "$480 000",
      owner: "Авиакомпания",
      ownerInitials: "АВ",
      modifiedAt: "23 сентября 2026",
      shared: true,
      starred: false,
    },
    {
      id: "plane-aist",
      name: "Самолёт «Аист»",
      kind: "air",
      price: "$1 200 000",
      owner: "Авиакомпания",
      ownerInitials: "АВ",
      modifiedAt: "21 сентября 2026",
      shared: false,
      starred: false,
    },
    {
      id: "boat-volna",
      name: "Катер «Волна»",
      kind: "water",
      price: "$64 000",
      owner: "Гражданские",
      ownerInitials: "ГР",
      modifiedAt: "19 сентября 2026",
      shared: true,
      starred: false,
    },
    {
      id: "patrol-strazh",
      name: "Патрульный «Страж»",
      kind: "special",
      price: "—",
      owner: "Полиция",
      ownerInitials: "ПО",
      modifiedAt: "17 сентября 2026",
      shared: false,
      starred: false,
    },
    {
      id: "ambulance-spas",
      name: "Автомобиль скорой «Спас»",
      kind: "special",
      price: "—",
      owner: "Скорая помощь",
      ownerInitials: "СП",
      modifiedAt: "15 сентября 2026",
      shared: false,
      starred: false,
    },
  ],
};
