import { Package, Pill, Shield, Sword, Utensils, Wrench } from "lucide-react";

import type { CatalogConfig } from "./catalog-types";

export const itemsConfig: CatalogConfig = {
  domain: "items",
  basePath: "/dashboard/items",
  metaTitle: "Предметы — каталог игровых предметов",
  metaDescription: "Каталог предметов проекта: оружие, экипировка, медицина, инструменты, еда и прочее.",
  title: "Предметы",
  subtitle: "Каталог игровых предметов: находите, группируйте и отслеживайте позиции.",
  addLabel: "Добавить предмет",
  addDialogTitle: "Добавить предмет",
  addDialogDescription: "Новый предмет появится в каталоге. Данные сохраняются в этом браузере.",
  namePlaceholder: "Например, Аптечка",
  defaultOwner: "Магазин 24/7",
  entryAddedMessage: "Предмет добавлен",
  newCategoryLabel: "Новая категория",
  searchPlaceholder: "Поиск по предметам и категориям...",
  categoriesTitle: "Категории",
  categoriesEmptyTitle: "Категорий пока нет",
  categoriesEmptyDescription: "Создайте категорию, чтобы упорядочить предметы.",
  allTitle: "Все предметы",
  viewLabel: "Вид каталога",
  kindFilterLabel: "Тип предмета",
  ownerColumn: "Где купить",
  sharedLabel: "В продаже",
  entryForms: ["предмет", "предмета", "предметов"],
  categoryForms: ["категория", "категории", "категорий"],
  kinds: [
    { value: "weapon", label: "Оружие", icon: Sword },
    { value: "gear", label: "Экипировка", icon: Shield },
    { value: "medical", label: "Медицина", icon: Pill },
    { value: "tool", label: "Инструмент", icon: Wrench },
    { value: "food", label: "Еда", icon: Utensils },
    { value: "misc", label: "Прочее", icon: Package },
  ],
  detailSections: [],
  categories: [
    { id: "weapons", name: "Оружие", count: 26, priceFrom: "от 1 200\u00A0₽", updatedAt: "12 мин назад" },
    { id: "ammo", name: "Боеприпасы", count: 15, priceFrom: "от 50\u00A0₽", updatedAt: "Вчера" },
    { id: "gear", name: "Экипировка", count: 32, priceFrom: "от 120\u00A0₽", updatedAt: "26 сентября" },
    { id: "medical", name: "Медицина", count: 12, priceFrom: "от 40\u00A0₽", updatedAt: "24 сентября" },
    { id: "tools", name: "Инструменты", count: 21, priceFrom: "от 80\u00A0₽", updatedAt: "22 сентября" },
    { id: "food", name: "Еда и напитки", count: 28, priceFrom: "от 5\u00A0₽", updatedAt: "19 сентября" },
  ],
  entries: [
    {
      id: "pistol-grom",
      name: "Пистолет «Гром-9»",
      kind: "weapon",
      price: "2 400\u00A0₽",
      owner: "Оружейный магазин",
      ownerInitials: "ОМ",
      modifiedAt: "5 минут назад",
      shared: true,
      starred: true,
    },
    {
      id: "shotgun-kaban",
      name: "Дробовик «Кабан»",
      kind: "weapon",
      price: "5 800\u00A0₽",
      owner: "Оружейный магазин",
      ownerInitials: "ОМ",
      modifiedAt: "2 часа назад",
      shared: true,
      starred: false,
    },
    {
      id: "ammo-9mm",
      name: "Патроны 9 мм (пачка)",
      kind: "weapon",
      price: "150\u00A0₽",
      owner: "Оружейный магазин",
      ownerInitials: "ОМ",
      modifiedAt: "Вчера",
      shared: true,
      starred: false,
    },
    {
      id: "vest-3",
      name: "Бронежилет 3 класса",
      kind: "gear",
      price: "3 200\u00A0₽",
      owner: "Магазин экипировки",
      ownerInitials: "МЭ",
      modifiedAt: "27 сентября 2026",
      shared: true,
      starred: true,
    },
    {
      id: "guard-uniform",
      name: "Форма охранника",
      kind: "gear",
      price: "450\u00A0₽",
      owner: "Магазин одежды",
      ownerInitials: "МО",
      modifiedAt: "26 сентября 2026",
      shared: true,
      starred: false,
    },
    {
      id: "first-aid",
      name: "Аптечка",
      kind: "medical",
      price: "300\u00A0₽",
      owner: "Аптека",
      ownerInitials: "АП",
      modifiedAt: "25 сентября 2026",
      shared: true,
      starred: false,
    },
    {
      id: "bandage",
      name: "Бинт стерильный",
      kind: "medical",
      price: "40\u00A0₽",
      owner: "Аптека",
      ownerInitials: "АП",
      modifiedAt: "24 сентября 2026",
      shared: true,
      starred: false,
    },
    {
      id: "lockpick",
      name: "Набор отмычек",
      kind: "tool",
      price: "900\u00A0₽",
      owner: "Чёрный рынок",
      ownerInitials: "ЧР",
      modifiedAt: "23 сентября 2026",
      shared: false,
      starred: false,
    },
    {
      id: "radio",
      name: "Рация",
      kind: "tool",
      price: "650\u00A0₽",
      owner: "Магазин 24/7",
      ownerInitials: "24",
      modifiedAt: "21 сентября 2026",
      shared: true,
      starred: true,
    },
    {
      id: "toolkit",
      name: "Набор инструментов",
      kind: "tool",
      price: "1 100\u00A0₽",
      owner: "Автомастерская",
      ownerInitials: "АМ",
      modifiedAt: "19 сентября 2026",
      shared: true,
      starred: false,
    },
    {
      id: "burger",
      name: "Бургер",
      kind: "food",
      price: "25\u00A0₽",
      owner: "Магазин 24/7",
      ownerInitials: "24",
      modifiedAt: "17 сентября 2026",
      shared: true,
      starred: false,
    },
    {
      id: "event-key",
      name: "Ключ-карта «Событие»",
      kind: "misc",
      price: "—",
      owner: "Администрация",
      ownerInitials: "АД",
      modifiedAt: "15 сентября 2026",
      shared: false,
      starred: false,
    },
  ],
};
