import { Building2, Car, House, Store, TreePine, Warehouse } from "lucide-react";

import type { CatalogConfig } from "./catalog-types";

export const propertyConfig: CatalogConfig = {
  domain: "property",
  basePath: "/property",
  metaTitle: "Имущество — каталог недвижимости и бизнесов",
  metaDescription: "Каталог имущества проекта: дома, квартиры, бизнесы, земельные участки, гаражи и склады.",
  title: "Имущество",
  subtitle: "Каталог имущества: находите, группируйте и отслеживайте объекты.",
  addLabel: "Добавить имущество",
  addDialogTitle: "Добавить имущество",
  addDialogDescription: "Новый объект появится в каталоге. Данные сохраняются в этом браузере.",
  namePlaceholder: "Например, Дом «Сосновый»",
  defaultOwner: "Агентство",
  entryAddedMessage: "Имущество добавлено",
  newCategoryLabel: "Новая категория",
  searchPlaceholder: "Поиск по имуществу и категориям...",
  categoriesTitle: "Категории",
  categoriesEmptyTitle: "Категорий пока нет",
  categoriesEmptyDescription: "Создайте категорию, чтобы упорядочить имущество.",
  allTitle: "Всё имущество",
  viewLabel: "Вид каталога",
  kindFilterLabel: "Тип имущества",
  ownerColumn: "Владелец",
  sharedLabel: "В продаже",
  entryForms: ["объект", "объекта", "объектов"],
  categoryForms: ["категория", "категории", "категорий"],
  kinds: [
    { value: "house", label: "Дом", icon: House },
    { value: "apartment", label: "Квартира", icon: Building2 },
    { value: "business", label: "Бизнес", icon: Store },
    { value: "land", label: "Участок", icon: TreePine },
    { value: "garage", label: "Гараж", icon: Car },
    { value: "warehouse", label: "Склад", icon: Warehouse },
  ],
  detailSections: [],
  categories: [
    { id: "houses", name: "Дома", count: 22, priceFrom: "от 95 000\u00A0₽", updatedAt: "12 мин назад" },
    { id: "apartments", name: "Квартиры", count: 48, priceFrom: "от 32 000\u00A0₽", updatedAt: "Вчера" },
    { id: "business", name: "Бизнесы", count: 17, priceFrom: "от 120 000\u00A0₽", updatedAt: "26 сентября" },
    { id: "land", name: "Земельные участки", count: 13, priceFrom: "от 18 000\u00A0₽", updatedAt: "24 сентября" },
    { id: "garages", name: "Гаражи", count: 31, priceFrom: "от 12 000\u00A0₽", updatedAt: "22 сентября" },
    { id: "warehouses", name: "Склады", count: 9, priceFrom: "от 75 000\u00A0₽", updatedAt: "19 сентября" },
  ],
  entries: [
    {
      id: "house-sosnovy",
      name: "Дом «Сосновый»",
      kind: "house",
      price: "185 000\u00A0₽",
      owner: "Агентство",
      ownerInitials: "АГ",
      modifiedAt: "5 минут назад",
      shared: true,
      starred: true,
    },
    {
      id: "cottage-lake",
      name: "Коттедж у озера",
      kind: "house",
      price: "320 000\u00A0₽",
      owner: "Агентство",
      ownerInitials: "АГ",
      modifiedAt: "2 часа назад",
      shared: true,
      starred: false,
    },
    {
      id: "apt-center",
      name: "Квартира в центре",
      kind: "apartment",
      price: "92 000\u00A0₽",
      owner: "Агентство",
      ownerInitials: "АГ",
      modifiedAt: "Вчера",
      shared: true,
      starred: false,
    },
    {
      id: "studio-metro",
      name: "Студия у метро",
      kind: "apartment",
      price: "48 000\u00A0₽",
      owner: "Агентство",
      ownerInitials: "АГ",
      modifiedAt: "27 сентября 2026",
      shared: true,
      starred: false,
    },
    {
      id: "penthouse-nebo",
      name: "Пентхаус «Небо»",
      kind: "apartment",
      price: "540 000\u00A0₽",
      owner: "Частный владелец",
      ownerInitials: "ЧВ",
      modifiedAt: "26 сентября 2026",
      shared: false,
      starred: true,
    },
    {
      id: "shop-247",
      name: "Магазин 24/7",
      kind: "business",
      price: "260 000\u00A0₽",
      owner: "Мэрия",
      ownerInitials: "МЭ",
      modifiedAt: "25 сентября 2026",
      shared: true,
      starred: false,
    },
    {
      id: "carwash",
      name: "Автомойка",
      kind: "business",
      price: "175 000\u00A0₽",
      owner: "Мэрия",
      ownerInitials: "МЭ",
      modifiedAt: "24 сентября 2026",
      shared: true,
      starred: false,
    },
    {
      id: "restaurant-pier",
      name: "Ресторан «У причала»",
      kind: "business",
      price: "410 000\u00A0₽",
      owner: "Частный владелец",
      ownerInitials: "ЧВ",
      modifiedAt: "23 сентября 2026",
      shared: false,
      starred: true,
    },
    {
      id: "land-12",
      name: "Участок 12 соток",
      kind: "land",
      price: "64 000\u00A0₽",
      owner: "Государство",
      ownerInitials: "ГС",
      modifiedAt: "21 сентября 2026",
      shared: true,
      starred: false,
    },
    {
      id: "farm",
      name: "Ферма «Заря»",
      kind: "land",
      price: "210 000\u00A0₽",
      owner: "Государство",
      ownerInitials: "ГС",
      modifiedAt: "19 сентября 2026",
      shared: true,
      starred: false,
    },
    {
      id: "garage-4",
      name: "Гараж на 4 места",
      kind: "garage",
      price: "58 000\u00A0₽",
      owner: "Агентство",
      ownerInitials: "АГ",
      modifiedAt: "17 сентября 2026",
      shared: true,
      starred: false,
    },
    {
      id: "warehouse-3",
      name: "Склад №3",
      kind: "warehouse",
      price: "120 000\u00A0₽",
      owner: "Государство",
      ownerInitials: "ГС",
      modifiedAt: "15 сентября 2026",
      shared: false,
      starred: false,
    },
  ],
};
