import {
  Bus,
  CarTaxiFront,
  ChefHat,
  Crosshair,
  Drill,
  Fish,
  Flame,
  Hammer,
  House,
  KeyRound,
  Leaf,
  type LucideIcon,
  Mail,
  Mountain,
  Package,
  Pickaxe,
  Search,
  Shovel,
  Sprout,
  Trash2,
  TreePine,
  Truck,
  Vault,
  Wheat,
  Zap,
} from "lucide-react";

export const jobIcons: Record<string, LucideIcon> = {
  shahter: Pickaxe,
  stroitel: Hammer,
  sobiratel: Leaf,
  povar: ChefHat,
  rybak: Fish,
  taksist: CarTaxiFront,
  kladoiskatel: Shovel,
  musorshik: Trash2,
  fermer: Wheat,
  gribnik: Sprout,
  ohotnik: Crosshair,
  karershik: Mountain,
  "voditel-avtobusa": Bus,
  lesorub: TreePine,
  pochtalon: Mail,
  elektrik: Zap,
  inkassator: Vault,
  pozharnyj: Flame,
  dalnoboishchik: Truck,
  zakladchik: Package,
  syshchik: Search,
  "grabitel-domov": House,
  ugonshchik: KeyRound,
};

export const fallbackJobIcon: LucideIcon = Drill;
